export const data = [
  {
    college: 'Karnataka state college',
    address: '5065 Mandrake Lane',
    university: "Yan'an University",
    district: 'Ljungskile',
    date: '27-09-2021',
    students: 393,
    id: 1,
  },
  {
    college: 'Karnataka state college',
    address: '596 Beilfuss Trail',
    university: 'Indian Institute of Technology, Kanpur',
    district: 'Sivers’k',
    date: '20-12-2021',
    students: 698,
    id: 2,
  },
  {
    college: 'Karnataka state college',
    address: '292 Toban Terrace',
    university: 'KDI School of Public Policy and Management',
    district: 'Kalāt-e Nāderī',
    date: '21-03-2022',
    students: 348,
    id: 3,
  },
  {
    college: 'Karnataka state college',
    address: '950 Muir Parkway',
    university: 'State University of Tetova',
    district: 'Kodinsk',
    date: '20-08-2021',
    students: 450,
    id: 4,
  },
  {
    college: 'Karnataka state college',
    address: '74677 3rd Park',
    university: 'University of Roorkee',
    district: 'Žagarė',
    date: '13-11-2021',
    students: 805,
    id: 5,
  },
  {
    college: 'Karnataka state college',
    address: '49 Becker Trail',
    university: 'Toyama Medical and Pharmaceutical University',
    district: 'Wijewo',
    date: '28-04-2022',
    students: 506,
    id: 6,
  },
  {
    college: 'Karnataka state college',
    address: '32445 Rigney Drive',
    university: 'Woosuk University',
    district: 'Shibīn al Qanāţir',
    date: '30-03-2022',
    students: 616,
    id: 7,
  },
  {
    college: 'Karnataka state college',
    address: '65 Esker Center',
    university: 'Université Abdou Moumouni de Niamey',
    district: 'Lille',
    date: '12-06-2021',
    students: 324,
    id: 8,
  },
  {
    college: 'Karnataka state college',
    address: '746 Montana Trail',
    university: 'Capella University',
    district: 'Hājīganj',
    date: '13-02-2022',
    students: 588,
    id: 9,
  },
  {
    college: 'Karnataka state college',
    address: '9438 Carey Pass',
    university: 'Shanghai Sanda University',
    district: 'Turtas',
    date: '30-07-2021',
    students: 560,
    id: 10,
  },
  {
    college: 'Karnataka state college',
    address: '39412 School Street',
    university: 'Universidad Técnica de Machala',
    district: 'Wuci',
    date: '25-04-2022',
    students: 703,
    id: 11,
  },
  {
    college: 'Karnataka state college',
    address: '4931 Spenser Center',
    university: 'Universidad Internacional de las Américas',
    district: 'Chacapalpa',
    date: '31-03-2022',
    students: 652,
    id: 12,
  },
  {
    college: 'Karnataka state college',
    address: '6873 Walton Road',
    university: 'University of Trieste',
    district: 'R S',
    date: '23-05-2022',
    students: 576,
    id: 13,
  },
  {
    college: 'Karnataka state college',
    address: '395 Farragut Point',
    university: "Centre Universitaire d'Oum El Bouaghi",
    district: 'Fengtai Chengguanzhen',
    date: '09-07-2021',
    students: 412,
    id: 14,
  },
  {
    college: 'Karnataka state college',
    address: '015 Scofield Center',
    university: "Université d'Evry Val d'Essonne",
    district: 'Qifang',
    date: '30-01-2022',
    students: 351,
    id: 15,
  },
  {
    college: 'Karnataka state college',
    address: '70 Sullivan Alley',
    university: 'Gebze Institute of Technology',
    district: 'Plácido de Castro',
    date: '10-03-2022',
    students: 497,
    id: 16,
  },
  {
    college: 'Karnataka state college',
    address: '7 Norway Maple Place',
    university: 'Kasem Bundit University',
    district: 'Oesena',
    date: '07-04-2022',
    students: 913,
    id: 17,
  },
  {
    college: 'Karnataka state college',
    address: '37 Thompson Parkway',
    university: 'Universidad Nacional Experimental "Francisco de Miranda"',
    district: 'Sidi Bousber',
    date: '04-11-2021',
    students: 516,
    id: 18,
  },
  {
    college: 'Karnataka state college',
    address: '7790 Haas Point',
    university: 'University of Ghana',
    district: 'Rio das Ostras',
    date: '06-07-2021',
    students: 490,
    id: 19,
  },
  {
    college: 'Karnataka state college',
    address: '203 Sunnyside Hill',
    university: 'College of St. Elizabeth',
    district: 'Pryluky',
    date: '13-04-2022',
    students: 819,
    id: 20,
  },
  {
    college: 'Karnataka state college',
    address: '8 Norway Maple Avenue',
    university: 'West Virginia University',
    district: 'Bobowo',
    date: '28-12-2021',
    students: 646,
    id: 21,
  },
  {
    college: 'Karnataka state college',
    address: '539 Oneill Avenue',
    university: 'Duquesne University',
    district: 'Tarkwa',
    date: '23-11-2021',
    students: 925,
    id: 22,
  },
];
